### PR TITLE
fix #133 - nil reference to CDV_LOCAL_SERVER

### LINKED ISSUE #133: [BUG] Can't load a file from documents directory into the webview / '_file_' prefix causes SIGBART on iOS
I recently uncovered a treasure trove of bugs with this plugin after migrating to 2.0. Previously we were on 1.1.19 and had no issues loading a local audio file into a waveform on iOS. For my current project we need to update our plugin to > 2.0 to be able to interface with Ionic Pro, however this completely broke loading in local files into the waveform container on iOS.

This is the line that does it: ` this.wavesurfer.load('_file_' + this.file.documentsDirectory.replace(/file:\/\//g, '')+ fileName);`

Now previously, on 1.1.19, this line worked as, but this does not work on 2.0:  `this.wavesurfer.load(this.file.documentsDirectory.replace(/file:\/\//g, '')+ fileName;`

I've tried using `'_file_'`, `"file://"` and `"cdvfile://"`. None work.

When trying with the `'_file_'` prefix, I get a SIGBART on iOS.

image

Bug 1: `self.CDV_LOCAL_SERVER` is getting set to nil somewhere
Bug 2: If I hard code the local server path, I get a SIGBART deep inside the engine code. Can post more on that later.

Is there something I'm missing here? I get that the webview now runs inside the local server with a different path, but how can i adjust my code to be able to load my waveform??

Help is needed urgently, thanks.

### PR DESCRIPTION
**Pull request by matejkramny**
issue is `self.CDV_LOCAL_SERVER` is set when server is started, not when the `_file_` route is set up.

The change sets up the `CDV_LOCAL_SERVER` path before both so that it's safely accessible in the file handler.

### CODE REVIEW

**Comment by tetpsy** [comment]
Hey @matejkramny 
Your merge request worked perfectly

Thanks so much man

life saver

**Comment by fuentes010** [comment]
Thanks @matejkramny, tested and works perfectly!

File: src/ios/CDVWKWebViewEngine.m [hunk 1]
```diff
@@ -755,10 +764,11 @@ -(void)setServerPath:(NSString *) path
     if (restart) {
         [self.webServer stop];
     }
-    NSString *serverUrl = self.CDV_LOCAL_SERVER;
+
+    __block NSString* basePath = self.CDV_LOCAL_SERVER;
```
Comment (jcesarmobile) [inline src/ios/CDVWKWebViewEngine.m]: Don't rename to `basePath` as we have the `self.basePath` and can be confusing

**Comment by matejkramny** [comment]
@jcesarmobile updated the variable. Thanks!

**Comment by jcesarmobile** [comment]
Thanks! merged

**Comment by dwieeb** [comment]
Thank you @matejkramny! Great work 💪

**Comment by dwieeb** [comment]
2.0.3 is published with this fix
