### PR TITLE
fix(ios): fix keyboard displacement bug in iOS 12 WKWebView

### LINKED ISSUE #176: Keyboard Dismissal Leaves Viewport Shifted in iOS 12 / XCode 10
I think it's a bug in ionic plugin (without the cordova-plugin-ionic-keyboard installed):
https://github.com/apache/cordova-ios/issues/417

### PR DESCRIPTION
**Pull request by booleanbetrayal**
Fixes #176 

credit: @KhanhPhamDinh

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
I'm seeing a "bounce" effect when completing a particular input and then programmatically focusing the next. This might need to be de-bounced or handled with some better state handling for that use-case.

**Comment by booleanbetrayal** [comment]
Worked in the timer debounce support for the programmatic input-focus issue (which caused a visual "bouncing" during an unnecessary `contentOffset` adjustment).

@KhanhPhamDinh - you might want to take a look to see how this differs from your original implementation.

File: src/ios/CDVWKWebViewEngine.m [hunk 1]
```diff
@@ -431,6 +444,37 @@ - (void)onAppWillEnterForeground:(NSNotification *)notification {
...
+{
+    if (timer != nil) {
+        [timer invalidate];
+    }
+}
+
+-(void)keyboardDisplacementFix
+{
+    WKWebView *webview = (WKWebView*) self.webView;
+    for (UIView* v in webview.subviews ){
```
Comment (ravron) [inline src/ios/CDVWKWebViewEngine.m]: Rather than iterating through the webview's subviews, you can just access [`webview.scrollView`](https://developer.apple.com/documentation/webkit/wkwebview/1614784-scrollview?language=objc).

Comment (booleanbetrayal) [reply src/ios/CDVWKWebViewEngine.m]: Simplified. Thanks @ravron

**Comment by KhanhPhamDinh** [comment]
> Worked in the timer debounce support for the programmatic input-focus issue (which caused a visual "bouncing" during an unnecessary `contentOffset` adjustment).
> 
> @KhanhPhamDinh - you might want to take a look to see how this differs from your original implementation.

Your welcome, @booleanbetrayal.

**Comment by booleanbetrayal** [comment]
Any change on getting this merged @dwieeb / @nphyatt?

There is a good explanation of the issue in https://github.com/apache/cordova-ios/issues/417 prior to realizing this was an Apple WKWebView issue we'd need to work around.

Thanks!

**Comment by ravron** [comment]
Note that there's detailed information on this `WKWebView` bug at [this Open Radar ticket](http://www.openradar.me/44655885).

**Comment by simtechpom** [comment]
@booleanbetrayal using this fork did solve the viewport problem in ios.

**Comment by booleanbetrayal** [comment]
@simtechpom - perhaps a discrepancy between when I forked this repo and what master is at now. Out of scope from this changeset. All the more reason to get this merged!

**Comment by bshafiee** [comment]
@manucorporat Could you please take a look at this and possibly merge? it basically renders our app useless and is a huge issue. Thanks in advance.

**Comment by mlynch** [comment]
So who has tested this? Just because it's a PR doesn't mean that you can't start using it. Would love some help making sure this doesn't break stuff.

**Comment by bshafiee** [comment]
I've not tested this patch yet Max, but I just dowgraded my keyboard plugin to the deprecated version and it works fine there:
```
cordova plugin rm cordova-plugin-ionic-keyboard
ionic cordova plugin add ionic-plugin-keyboard && npm install --save @ionic-native/native-keyboard
```
Not really sure why it doens't happen there 🤷‍♂️

**Comment by mlynch** [comment]
Okay resolved conflicts and merged. Testing something quick and then will be in 2.2.4 tonight

**Comment by mlynch** [comment]
2.2.4 released with this PR, thanks for the contribution and for others adding their feedback!

**Comment by bshafiee** [comment]
I just tried `2.2.5` and it works fine, no scrolling issue and no convertFileSrc issue on ios either (will check for Android too). Thanks @mlynch  for merging and thanks @booleanbetrayal for the PR! 👏  😍

**Comment by booleanbetrayal** [comment]
Great! Hopefully this gets fixed upstream on Apple's end at some point and we can limit the scope of those keyboard listeners.

**Comment by risikoruk** [comment]
Still happens to me with webview 2.2.5 and keyboard 2.1.3 installed. Specifically when focusing on an input in a login screen in Framework7. Elements get pushed top and at keyboard closing the height isn't adjusted

**Comment by andrejwright** [comment]
I am finding that it isn't working for me either

**Comment by kieranbehn** [comment]
I am also still experiencing this issue using cordova-plugin-ionic-webview 2.3.1 and cordova-plugin-ionic-keyboard 2.1.3

**Comment by daniellizik** [comment]
I'm on cordova-plugin-ionic-webview 2.3.2 and can still reproduce this issue

**Comment by jayordway** [comment]
I am on cordova-plugin-ionic-webview 4.0.0 and this is still an issue.

**Comment by ananthaarni** [comment]
I have the same issue and it's show stopper

**Comment by ericpointofrental** [comment]
Downgrading to `ionic-plugin-keyboard@2.2.1` and `cordova-plugin-ionic-webview@2.2.5` worked for my Ionic 4 app. Not even close to ideal, but more ideal than having the screen jump all over the place whenever the user uses my messaging input.

**Comment by sajallimbu** [comment]
Issue still exists in ios12 with Ionic 4 wkwebview.
Causes the viewport to bounce when shifting focus from one field to another.
